const URL = {
    GET_INITIAL_IMAGES: `images/initialImages`,
    GET_USER_INFO: 'user/initialInfo',
    GET_FOREIGN_USER_INFO: 'user/getUserInfo',
    UPDATE_USER_INFO: 'user/updateUser',
    UPDATE_USER_PASSWORD: 'user/updatePassword',
    FOLLOW: 'user/followCourse',
    UNFOLLOW: 'user/unfollowCourse',
    COMPLETE: 'user/endCourse',
    LIKE: 'user/likeCourse',
    DISLIKE: 'user/dislikeCourse',
    LOGIN: 'login',
    LOGOUT: 'logout',
    REGISTER: 'register',
    FORGOT_PASSWORD: 'forgotPassword',
    GET_CATEGORIES: 'getCategories',
    CREATE_COURSE: 'courses/create',
    UPDATE_COURSE: 'courses/update',
    REMOVE_COURSE: 'courses/remove',
    GET_ALL_COURSES: 'courses/getAll',
    GET_COURSE: 'courses/getById',
    GET_OWNED_COURSES: 'courses/getOwned',
    GET_FOLLOWED_COURSES: 'courses/getFollowed',
    GET_COMPLETED_COURSES: 'courses/getEnded',
    GET_USER_COURSES: 'courses/getByUserId',
    SEARCH_COURSES: 'courses/search',
    GET_COMMENTS: 'getComments',
    CREATE_COMMENT: 'createComment',
    REMOVE_COMMENT: 'removeComment',
}

export default URL